apiVersion: v1
kind: Service
metadata:
  name: compute-redis-main
  namespace: merak
  labels:
    app: redis
    role: main
    tier: backend
spec:
  ports:
  - protocol: TCP
    port: 30051
    targetPort: compute-redis
  selector:
    app: redis
    role: main
    tier: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compute-redis-main
  namespace: merak
  labels:
    app: redis
    role: main
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        role: main
        tier: backend
    spec:
      containers:
      - name: main
        image: "redis:7.0.0"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
          name: compute-redis