# MIT License
# Copyright(c) 2022 Futurewei Cloud
#     Permission is hereby granted,
#     free of charge, to any person obtaining a copy of this software and associated documentation files(the "Software"), to deal in the Software without restriction,
#     including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and / or sell copies of the Software, and to permit persons
#     to whom the Software is furnished to do so, subject to the following conditions:
#     The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#     FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
#     WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
images:
- name: meraksim/merak-compute
  newTag: test
resources:
- test.driver.yaml
- temporal.test.yaml
# Exclude Merak Network
patches:
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: Service
    metadata:
      name: merak-network-service
      namespace: merak
- patch: |-
    $patch: delete
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: merak-network
      namespace: merak
- patch: |-
    $patch: delete
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: redis-network
      namespace: merak
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: Service
    metadata:
      name: merak-redis-network
      namespace: merak
# Exclude Merak Scenario
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: Service
    metadata:
      name: scenario-manager-service
      namespace: merak
- patch: |-
    $patch: delete
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: scenario-manager
      namespace: merak
- patch: |-
    $patch: delete
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: scenario-redis-master
      namespace: merak
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: Service
    metadata:
      name: scenario-redis-master
      namespace: merak
# Exclude Merak Topology
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: Service
    metadata:
      name: merak-topology-service
      namespace: merak
- patch: |-
    $patch: delete
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: merak-topology
      namespace: merak
- patch: |-
    $patch: delete
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: topology-redis-master
      namespace: merak
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: Service
    metadata:
      name: topology-redis-master
      namespace: merak
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: merak-topology
      namespace: merak
- patch: |-
    $patch: delete
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: merak-topology
- patch: |-
    $patch: delete
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: sdn-controller
      namespace: merak
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: Service
    metadata:
      name: sdn-controller
      namespace: merak

# # Temporal Helm Chart
# helmCharts:
# - releaseName: temporal
#   repo: https://charts.wener.tech
#   name: temporal
#   version: 0.15.1
#   valuesInline:
#     server:
#       replicatCount: 1
#     cassandra:
#       config:
#         cluster_size: 1
#     prometheus:
#       enabled: false
#     grafana:
#       enabled: false
#     elasticsearch:
#       enabled: false
