---
apiVersion: v1
kind: Service
metadata:
  name: temporal-frontend
spec:
  selector:
    app: temporalite
  ports:
    - protocol: TCP
      name: temporal-frontend
      port: 7233
      targetPort: temporal
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporalite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporalite
  template:
    metadata:
      labels:
        app: temporalite
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: temporalite
        image: meraksim/temporalite:dev
        imagePullPolicy: Always
        ports:
          - containerPort: 7233
            name: temporal
