apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# DB
- db/ignite_alcor_dpm.yaml
- db/ignite_alcor_ip.yaml
- db/ignite_alcor_mac.yaml
- db/ignite_alcor_ncm.yaml
- db/ignite_alcor_port.yaml
- db/ignite_alcor.yaml

# Services
- services/api-gateway.yaml
- services/dpm_manager.yaml
- services/elastic_ip_manager.yaml
- services/gateway_manager.yaml
- services/mac_manager.yaml
- services/network_config_manager.yaml
- services/node_manager.yaml
