apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
- ../alcor
- https://github.com/networkop/meshnet-cni.git/manifests/base
images:
- name: yanmo96/network_config_manager
  newName: yongqi166/ncm
  newTag: "1.0"
- name: meraksim/merak-compute-vm-worker
  newTag: ovs-batch
- name: meraksim/merak-compute-vm
  newTag: ovs-batch
replicas:
# Merak Service
- name: merak-compute-vm-worker
  count: 1
# Alcor Service
- name: apimanager
  count: 1
- name: dataplanemanager
  count: 1
- name: eipmanager
  count: 1
- name: gatewaymanager
  count: 1
- name: macmanager
  count: 1
- name: netwconfigmanager
  count: 1
- name: nodemanager
  count: 1
# Alcor DB
- name: ignite-alcor-dpm
  count: 1
- name: ignite-alcor-ip
  count: 3
- name: ignite-alcor-mac
  count: 1
- name: ignite-alcor-ncm
  count: 1
- name: ignite-alcor-port
  count: 1
- name: ignite-alcor
  count: 1
helmCharts:
- releaseName: temporal
  repo: https://charts.wener.tech
  name: temporal
  version: 0.15.1
  includeCRDs: true
  valuesInline:
    server:
      replicatCount: 1
    cassandra:
      config:
        cluster_size: 1
    prometheus:
      enabled: false
    grafana:
      enabled: false
    elasticsearch:
      enabled: false
