apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
replicas:
- name: merak-compute-vm-worker
  count: 1
helmCharts:
- releaseName: temporal
  repo: https://charts.wener.tech
  name: temporal
  version: 0.15.1
  includeCRDs: true
  valuesInline:
    server:
      replicatCount: 1
    cassandra:
      config:
        cluster_size: 1
    prometheus:
      enabled: false
    grafana:
      enabled: false
    elasticsearch:
      enabled: false
